### ISSUE TITLE
Dev content review

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-cloud-openshift-operator#30]
- [x] 20 -> 30 mins
- [x] sandbox -> playground and use the playground link directly
- **Additional prerequisites**
  - [x] are you sure need docker? only see all `oc` and `mvn` commands. The `docker pull` is not necessary
  - [x] make sure users log into their cluster 
- [x] **Accessing an OpenShift cluster** should be moved to **Additional prerequisites**
  - ask users go to playground or logon to the cluster system
- **Installing the Operators**
  - [x] run `oc api-resources --api-group=kafka.strimzi.io` to confirm strimzi operator is installed
- **Deploying the system and inventory applications to OpenShift**
  - "...and build the Docker imagesDocker images. Then, you need to push the images to the internal OpenShift registry and deploy the images by using the Open Liberty Operator." 
    - [x]  Do you mean build/push be done by build.yaml?
  - [x] no need to do `docker pull`
  - **Building and pushing the images**
    - [x] "...are your binary (local) files, which are streamed to OpenShift for the build. "
      - which files will be streamed? `.war` file, that's why need to run `mvn install` and `mvn package`
- **Accessing the inventory application**
  - [x] "For example, ...." not clear to me
- **Scaling up the system application**
  - [ ] playground does not work well after scaling up the system to 3
    - Revisit the inventory, data was not changed
- [ ] in the "What you’ll learn" section, use system and inventory microservice, so should use "`system/inventory` microservice" instead of "`system/inventory` application"?

**Comment by MaiHameed** [comment]
>  playground does not work well after scaling up the system to 3

Not sure why, looking into this.

**Comment by gkwan-ibm** [comment]
Cannot reproduce this issue " playground does not work well after scaling up the system to 3" in playground

**Comment by MaiHameed** [comment]
Cannot reproduce the issue either after trying it a few times in the playground, everything works as expected for me.
