### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/draft-guide-cloud-openshift-operator#36]
- "Prerequisites"
  - [x] Any reason `oc` isn't included in the list?

- "Additional prerequisites"
   - [x] The guide assumes people know about `oc` and they have it installed on their environment. What if this is the first OpenShift guide they start? Maybe add something about `oc` and how to be installed? Or maybe point to another guide that people should go through before this guide. (just thinking out loud...)
   - [x] "... You can use their ..." paragraph: remove "their" as 
   - [x] "Once you have access to a cluster, ...before proceeding with the guide.": What do you think about instructing people to run `oc version` and the sample output to ensure they are logged in?

- "Installing the Operators"
  - [x] "The Open Liberty Operator introduces new CRDs..." I'd suggest adding a sentence like the following to the end of this paragraph: "The Open LIberty Operator watches changes to instances of the OpenLibertyApplication and creates Kubernetes resources based on the config defined in the CRD instance."
  - [x] How should the output of `oc api-resources --api-group=kafka.strimzi.io` look like?
  - [x] Thoughts on adding how users can see the operators are installed successfully from the OpenShift dashboard?

- "Deploying the Kafka service to OpenShift"
  - [x] "Deploying the Kafka service to OpenShift" -> "Deploying the Kafka cluster to OpenShift"
  - [x] Does `oc get kafka/kafka-cluster` actually say if the Kafka cluster is setup properly? How should users know when to go to the next step in the guide? I think people need to run something like `oc get kafka/kafka-cluster -o yaml` and check the `status` section to know when the cluster is up and running.

- "Deploying the images"
  - [x] "The `applicationImage` parameter value is the only necessary parameter, and can be set by using the `<project-name>/<image-stream-name>[:tag]` format." --> "The `applicationImage` parameter defines what container image should be deployed as part of the `OpenLibertyApplication`. This parameter should follow the `<project-name>/<image-stream-name>[:tag]` format."
  - [x] "By default, the operator automatically redeploys applications when it detects a new image was pushed into the ImageStream." -> I'd suggest to reword this paragraph to something like "One of the benefits of using `ImageStream` is that the Operator redeploys the application when it detects a new image is pushed into the `ImageStream`."
  - [x] "If you are using an external image, you can define the pull policy by using a pullPolicy configuration parameter." I think this can be removed as people might be confused what is pull policy and how is it related to this guide. Thinking out loud...
  - [x] I'd suggest to show the output of `oc get OpenLibertyApplications` and say something about the "Reconcile" state being true meaning that the operator was able to successfully process the OpenLibertyApplication instances.

**Comment by AustinSeto** [comment]
Addressed all comments and implemented suggestions in #37
