### ISSUE TITLE
ID review

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/draft-guide-cloud-openshift-operator#42]
I've opened #43 to make some basic ID edits. The comments below are for conceptual questions and other issues I wasn't sure how best to address.

The title of the guide is not showing up on the draft site for some reason. 

## What you'll learn
- In the PR, I reordered some of the info so that the discussion of Operators in general comes before references to the OL and Strimzi Operators. I think there could still be a little more introductory info about operators, even just a sentence or two more, similar to the info for OpenShift. I noticed there was also a short paragraph about Kubernetes in the https://openliberty.io/guides/cloud-openshift.html[Deploying microservices to OpenShift] guide, not sure if that info would be useful here as well? 

- `The inventory microservice subscribes to that information so that it can keep an updated list of all the systems and their current system loads.`
Is there more than one system? This is confusing because the microservice is "system" singular, but the `inventory` microservice lists more than one "system"? Or are there two different uses of the term system here? If so, should distinguish one from the other somehow

- `The current inventory of systems can be accessed via the /systems REST endpoint. `
Is this part of the guide? If so better to discuss when you get to it. If not do you need to mention it? Seems unconnected to the other information here. It might be better to move it to the "Accessing..." section, where the user actually accesses the REST endpoint.

- There are a number of steps in this guide- installing, deploying, accessing, scaling. It might be helpful to give the user a brief overview of the sub-tasks so they can orient themselves as they work through the guide.

## Additional prerequisites

- `Before you can deploy your microservices, you must gain access to a cluster on OpenShift and have an OpenShift client installed.`
There is discussion about how to get access to OS cluster, but installing the OS client isn't explained anywhere, why or how.

- `You should see an asterisk (*) beside the project guide.`
Sample results would be helpful here

- the https://openliberty.io/guides/cloud-openshift.html[Deploying microservices to OpenShift] guide has a prereq for docker as well- is that needed here? It also has a prereq for the CLI, which is needed here.

## Installing the Operators
- `To install the two Operators, navigate to the web console, then to Operators > OperatorHub on the sidebar. `
This is the first mention of "the web console" in this guide. There's no explanation of what it is or how to find it. I know this means the OS console but the guide should introduce it somehow. Is this the only step that requires the console? Can the installation be done from the CLI? The user should know why they're going to the console only for this step (if that's the best way to install).

- `The Open Liberty Operator introduces new CRDs, including the OpenLibertyApplication.`
Looking at the example results, `OpenLibertyApplication` is the "KIND", while the name is `openlibertyapplications`. There is inconsistency throughout the guide between `OpenLibertyApplication` in some places and `OpenLibertyApplications` in others, but from looking at these results the name of the CRD is `openlibertyapplications`. Confirm which name is correct and use it consistently

- `Run the following command to view all the supported API resources available through the Open Liberty Operator:`
...
`You see the following output, which shows the custom resource definitions (CRDs) that are installed by the Open Liberty Operator`

In the command, you  view the "resources" that are "available", but the output shows the "CRDs" that are "installed". Are all the available resources also installed? It's not clear. Also, this section is about installing the Operators. If the Operators install resources there needs to be some explanation of that. The distinction between Operators and resources isn't clear. Same issue with the Strimzi Operator.

## Deploying the system and inventory applications to OpenShift

- `To deploy the Open Liberty system and inventory applications...`
In the introduction, `system` and `inventory` are referred to as "microservices". Here they are "applications". Pick one term and use it  consistently.

- `One of the benefits of using ImageStream is that the operator redeploys the application when it detects a new image is pushed into the ImageStream`
What is `ImageStream`. Is it the same as the image stream object mentioned earlier? It's not defined here or in the example yaml. If it is image stream object, use that term consistently.

- `Update the value of the bootstrap address variable to the required values. You can find the bootstrap address by running the following command:`
Example results would be helpful here. 
- `You can also substitute OpenLibertyApplications with the short form olapps.` If its useful to use shortnames you should mention/explain them back where they are listed in CRDs. 

## Scaling up the system application

- `Revisit the inventory application and you now see three elements`
Should be more clear that the user views the rest endpoint here through the same URL in the previous step. Also, is there a more precise term to use than "elements"? Perhaps "replicas"? "instances?

**Comment by AustinSeto** [comment]
Hi David, I'll address your issues and questions.

> The title of the guide is not showing up on the draft site for some reason.

I've noticed that as well, I'm not sure what is causing this as the title should be included the README at the top. 

>  I noticed there was also a short paragraph about Kubernetes in the Deploying microservices to OpenShift guide, not sure if that info would be useful here as well?

Saw the addition of the mention of Kubernetes Operators in your PR, I think it's a good choice to add that. I think it's fair to add something about Kubernetes itself. I think adding a link to the Kubernetes guide is worth it. In fact I think it may be worth replacing the link to the previous OpenShift guide that is meant for OpenShift 3 (see https://github.com/OpenLiberty/guide-cloud-openshift/pull/69 and issue https://github.com/openliberty/guide-cloud-openshift/issues/65)

> Is there more than one system? This is confusing because the microservice is "system" singular, but the inventory microservice lists more than one "system"? Or are there two different uses of the term system here? If so, should distinguish one from the other somehow

The system/inventory application is the sample application used in many of our guides and it can be used with multiple system microservices such as in the [asynchronous guide](https://github.com/OpenLiberty/guide-microprofile-rest-client-async/) but it is done here with only a single system microservice that is tracked.

> Is this part of the guide? If so better to discuss when you get to it. If not do you need to mention it? Seems unconnected to the other information here. It might be better to move it to the "Accessing..." section, where the user actually accesses the REST endpoint.

It's part of the description of the sample application the users will see upon completion so they know what to expect. I think we've had pretty similar in other guides. I'll check a few other guides and move it if I'm wrong here. 

> There are a number of steps in this guide- installing, deploying, accessing, scaling. It might be helpful to give the user a brief overview of the sub-tasks so they can orient themselves as they work through the guide.

We could add more subsections if that's what you mean? But if you remove sample outputs and copy-paste buttons for commands, I think most of the sections already are fairly small, only a few paragraphs. So adding more subsections so users can see their progress in the table of contents might make it so we have too many small sections which I'm not sure is desired. 

> Sample results would be helpful here

Sure I can add that and see how it looks with the rest of the guide. 

> the Deploying microservices to OpenShift guide has a prereq for docker as well- is that needed here? It also has a prereq for the CLI, which is needed here.

Docker is not needed for this guide and is in fact not supported for OpenShift 4 (see https://github.com/openliberty/guide-cloud-openshift/issues/65)

> This is the first mention of "the web console" in this guide. There's no explanation of what it is or how to find it. I know this means the OS console but the guide should introduce it somehow. Is this the only step that requires the console? Can the installation be done from the CLI? The user should know why they're going to the console only for this step (if that's the best way to install).

Understood, I'll make a small addition to that section to mention the web console.

> Looking at the example results, OpenLibertyApplication is the "KIND", while the name is openlibertyapplications. There is inconsistency throughout the guide between OpenLibertyApplication in some places and OpenLibertyApplications in others, but from looking at these results the name of the CRD is openlibertyapplications. Confirm which name is correct and use it consistently

> In the command, you view the "resources" that are "available", but the output shows the "CRDs" that are "installed". Are all the available resources also installed? It's not clear. Also, this section is about installing the Operators. If the Operators install resources there needs to be some explanation of that. The distinction between Operators and resources isn't clear. Same issue with the Strimzi Operator.

Will look into these two

> In the introduction, system and inventory are referred to as "microservices". Here they are "applications". Pick one term and use it consistently.

> What is ImageStream. Is it the same as the image stream object mentioned earlier? It's not defined here or in the example yaml. If it is image stream object, use that term consistently.

Will change these

> Update the value of the bootstrap address variable to the required values. You can find the bootstrap address by running the following command:
> Example results would be helpful here.

Will also add this and see how it looks

> If its useful to use shortnames you should mention/explain them back where they are listed in CRDs.

Understood, I'll add it to that section.

> Should be more clear that the user views the rest endpoint here through the same URL in the previous step. Also, is there a more precise term to use than "elements"? Perhaps "replicas"? "instances?

That's fair. Perhaps something similar to "you will now see three instances of the system microservice listed in the inventory endpoint" could be good.

**Comment by dmuelle** [comment]
Thanks Austin- just to clarify one of my comments:

>There are a number of steps in this guide- installing, deploying, accessing, scaling. It might be helpful to give the user a brief overview of the sub-tasks so they can orient themselves as they work through the guide.

I meant to suggest adding a short paragraph to the `What you'll learn` section that walks through the subtasks. Right now, the only explicit summary/overview of the task is a single sentence:

`You will learn how to deploy an application to Red Hat OpenShift by using Kubernetes Operators.`

But that's not a complete picture of what the user will do, which also includes installing the operators, accessing the inventory service and scaling the application. I think in a couple sentences you could summarize the subtasks- essentially the top-level headings in the sidebar TOC between `Installing the Operators` and `Scaling up the System application`. A summary would not only help the user mentally map the exercise but also provide some context as to why they should care about the operators.

**Comment by AustinSeto** [comment]
Ah I see what you mean now. Yea that is definitely something that can be added. I'll be sure to include something like that as I address the other comments and change things!

**Comment by AustinSeto** [comment]
Made PR #44 with changes to address previous comments
